#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v21
# autospec commit: 94c6be0
#
Name     : can-utils
Version  : 2025.01
Release  : 9
URL      : https://github.com/linux-can/can-utils/archive/v2025.01/can-utils-2025.01.tar.gz
Source0  : https://github.com/linux-can/can-utils/archive/v2025.01/can-utils-2025.01.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0
Requires: can-utils-bin = %{version}-%{release}
Requires: can-utils-license = %{version}-%{release}
BuildRequires : buildreq-cmake
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
<p align="center">
<img src="https://github.com/linux-can/can-logos/raw/master/png/SocketCAN-logo-60dpi.png" alt="SocketCAN logo"/>
</p>

%package bin
Summary: bin components for the can-utils package.
Group: Binaries
Requires: can-utils-license = %{version}-%{release}

%description bin
bin components for the can-utils package.


%package dev
Summary: dev components for the can-utils package.
Group: Development
Requires: can-utils-bin = %{version}-%{release}
Provides: can-utils-devel = %{version}-%{release}
Requires: can-utils = %{version}-%{release}

%description dev
dev components for the can-utils package.


%package license
Summary: license components for the can-utils package.
Group: Default

%description license
license components for the can-utils package.


%prep
%setup -q -n can-utils-2025.01
cd %{_builddir}/can-utils-2025.01
pushd ..
cp -a can-utils-2025.01 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1738345525
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1738345525
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/can-utils
cp %{_builddir}/can-utils-%{version}/LICENSES/GPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/can-utils/9a2473b1af68a99d91b786625fcf075c2b24c35f || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/asc2log
/V3/usr/bin/bcmserver
/V3/usr/bin/can-calc-bit-timing
/V3/usr/bin/canbusload
/V3/usr/bin/candump
/V3/usr/bin/canfdtest
/V3/usr/bin/cangen
/V3/usr/bin/cangw
/V3/usr/bin/canlogserver
/V3/usr/bin/canplayer
/V3/usr/bin/cansend
/V3/usr/bin/cansequence
/V3/usr/bin/cansniffer
/V3/usr/bin/isobusfs-cli
/V3/usr/bin/isobusfs-srv
/V3/usr/bin/isotpdump
/V3/usr/bin/isotpperf
/V3/usr/bin/isotprecv
/V3/usr/bin/isotpsend
/V3/usr/bin/isotpserver
/V3/usr/bin/isotpsniffer
/V3/usr/bin/isotptun
/V3/usr/bin/j1939-timedate-cli
/V3/usr/bin/j1939-timedate-srv
/V3/usr/bin/j1939acd
/V3/usr/bin/j1939cat
/V3/usr/bin/j1939spy
/V3/usr/bin/j1939sr
/V3/usr/bin/log2asc
/V3/usr/bin/log2long
/V3/usr/bin/mcp251xfd-dump
/V3/usr/bin/slcan_attach
/V3/usr/bin/slcand
/V3/usr/bin/slcanpty
/V3/usr/bin/testj1939
/usr/bin/asc2log
/usr/bin/bcmserver
/usr/bin/can-calc-bit-timing
/usr/bin/canbusload
/usr/bin/candump
/usr/bin/canfdtest
/usr/bin/cangen
/usr/bin/cangw
/usr/bin/canlogserver
/usr/bin/canplayer
/usr/bin/cansend
/usr/bin/cansequence
/usr/bin/cansniffer
/usr/bin/isobusfs-cli
/usr/bin/isobusfs-srv
/usr/bin/isotpdump
/usr/bin/isotpperf
/usr/bin/isotprecv
/usr/bin/isotpsend
/usr/bin/isotpserver
/usr/bin/isotpsniffer
/usr/bin/isotptun
/usr/bin/j1939-timedate-cli
/usr/bin/j1939-timedate-srv
/usr/bin/j1939acd
/usr/bin/j1939cat
/usr/bin/j1939spy
/usr/bin/j1939sr
/usr/bin/log2asc
/usr/bin/log2long
/usr/bin/mcp251xfd-dump
/usr/bin/slcan_attach
/usr/bin/slcand
/usr/bin/slcanpty
/usr/bin/testj1939

%files dev
%defattr(-,root,root,-)
/V3/usr/lib64/libisobusfs.so
/usr/include/isobusfs_cmn.h
/usr/include/isobusfs_cmn_cm.h
/usr/lib64/libisobusfs.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/can-utils/9a2473b1af68a99d91b786625fcf075c2b24c35f
